186 unify extension nams
HL7Austria/ELGA-MOPED-R5 pull request #196
Opened 2024-10-24 08:51 UTC by simonesan

Da laut sushi Extension Namen mit einem großen Buchstaben anfangen müssen, habe ich die in UpperCamelCase belassen.
Ansonsten habe ich alle Bezeichnungen auf deutsch geändert und die file Namen vereinheitlicht. Fürs Front-End habe ich die Bezeichnung der Extensions auf lowerCamelCase geändert, damit sie zumindest dort richtig sind.

2024-10-25 05:50 UTC, simonesan commented
Es sollte jetzt alles einheitlich sein, hab nur 2 kleine Fragen:
soll ich sowas wie coverageEligibilityRequestRef oder claimRef auch auf deusch umändern?
soll ich die neuen bezeichungen auch im Exel tabel nachziehen?

2024-10-29 08:48 UTC, alackerbauer commented
> Es sollte jetzt alles einheitlich sein, hab nur 2 kleine Fragen: soll ich sowas wie coverageEligibilityRequestRef oder claimRef auch auf deusch umändern? soll ich die neuen bezeichungen auch im Exel tabel nachziehen?

Ich denke, die Refs auf Ressourcen-Namen sollten wir in dem Fall auf englisch belassen. Die Änderungen ins Excel nachziehen wäre sehr hilfreich!

2024-10-29 08:49 UTC, alackerbauer commented
@simonesan sollen wir den PR schließen und das mit dem Excel in einem separaten Ticket erledigen?

2024-10-29 08:53 UTC, alackerbauer requested changes

2024-10-29 08:53 UTC, alackerbauer commented on input/fsh/examples/Test1/moped-test-1-coverageEligibility.fsh
> +* extension[+].url = "http://example.org/StructureDefinition/moped-ext-premiumClass"
das wäre Sonderklasse

2024-10-29 08:53 UTC, alackerbauer commented on input/fsh/extensions/moped-ext-KonstenmeldungARK.fsh
> +Id:           moped-ext-konstenmeldungArk
ich denke hier wäre es besser `kostenmeldungARK` zu schreiben

2024-10-29 08:53 UTC, alackerbauer commented on input/fsh/extensions/moped-ext-PremiumClass.fsh
> +Id: moped-ext-premiumClass
das wäre Sonderklasse

2024-10-29 08:53 UTC, alackerbauer commented on input/fsh/extensions/moped-ext-PunkteLDFPauschale.fsh
> +Id:           moped-ext-PunkteLdfPauschale
sollte punkte hier klein starten?

2024-10-29 08:53 UTC, alackerbauer commented on input/fsh/extensions/moped-ext-PunkteLDFPauschale.fsh
> +Id:           moped-ext-PunkteLdfPauschale
LDF kann auch groß belassen werden weil es schon ein Akronym ist

2024-10-29 08:53 UTC, alackerbauer commented on input/fsh/extensions/moped-ext-RechnungsnummerKHLGF.fsh
> +Id:           moped-ext-rechnungsnummerKhlgf
start mit kleinem `r` ok, KHLGF würde ich groß belassen, weil es ein Akronym ist

2024-10-29 08:54 UTC, simonesan commented
> @simonesan sollen wir den PR schließen und das mit dem Excel in einem separaten Ticket erledigen?

Ja ist vermutlich besser, ich erstell ein Issue dafür

2024-10-29 09:18 UTC, simonesan commented
Hier ist das Follow-up Issue für das Excel File:
https://github.com/HL7Austria/ELGA-MOPED-R5/issues/234

2024-10-29 09:20 UTC, alackerbauer approved these changes

2024-10-29 09:20 UTC, merged