86 update test 2
HL7Austria/ELGA-MOPED-R5 pull request #249
Opened 2024-10-31 13:01 UTC by simonesan

Enthält Änderungen für #86.
Achtung ist nicht der einzige Branch für das Issue.

2024-10-31 16:20 UTC, 1anja1 requested changes
Bitte Procedure und Condition von Testfall 2 nochmal überprüfen. Dies ist die endgültige Version von Testfall 1:
Procedure:
```
Instance: Test1Procedure1
InstanceOf: MOPEDProcedure
Usage: #example
* id = "Test1Procedure1"
* identifier[MOPEDProcedureIdentifier].type = https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier#RI
* identifier[MOPEDProcedureIdentifier].value = "1024000028urn:oid:1.3.6.1.4.1.36124.5.9140AN01024-08-08T08:50"
* code[0] = $LKFmedizinischeEinzelleistungen#AN010 "Polysomnographie im Schlaflabor (LE=je Behandlungstag)"
* subject = Reference(Patient/Test1Patient)
* encounter = Reference(MOPEDEncounter/Test1MOPEDEncounter)
* occurrenceDateTime = "2024-08-08T08:50:00+02:00"
* performer.actor = Reference(MOPEDOrganizationAbteilung/Test1OrganizationAbteilung1)
* performer.onBehalfOf = Reference(HL7ATCoreOrganization/Test1OrganizationHerzJesuKrankenhaus)
* status = #completed
```
Condition:
```
Alias: $icd-10 = http://hl7.org/fhir/sid/icd-10

Instance: Test1Condition1
InstanceOf: MOPEDCondition
Usage: #example
* id = "Test1Condition1"
* identifier[MOPEDConditionIdentifier].type = https://termgit.elga.gv.at/ValueSet/hl7-at-patientidentifier#RI
* identifier[MOPEDConditionIdentifier].value = "1024000028urn:oid:1.3.6.1.4.1.36124.5.9140G47.3"
* code.coding[ICD10] = $icd-10#G47.3 "Sleep Apnea"
* code.coding[HDG] = $LKFHauptdiagnosegruppen#HDG01.31 "TBD"
* subject = Reference(Patient/Test1Patient)
* clinicalStatus = #active
* encounter = Reference(MOPEDEncounter/Test1MOPEDEncounter)
* verificationStatus = #confirmed
```

2024-10-31 16:22 UTC, 1anja1 commented
> @1anja1 wurden diese Änderungen bereits in die upgedateten Test-Ressourcen übernommen?

Nein der Teil 1 des POC in der Postman collection muss erst noch nachgezogen werden. Oder was hast du gemeint? @alackerbauer

2024-11-04 08:43 UTC, simonesan commented
@1anja1 wie kommst du auf den wert von identifier[MOPEDConditionIdentifier].value?

im IG seht die formel "Aufnahmezahl+ICD10Code+Procedure.occurrence(YYYY-MM-DDTHH:MM)" für procedure
du hast de den wert "1024000028urn:oid:1.3.6.1.4.1.36124.5.9140AN01024-08-08T08:50" 
1024-08-08T08:50 ist aber nicht der richtige timestamp? und was ist darin der ICD10 code und die Aufnahmezahl?

für Conditon ist die formel "MOPED Identifier = Aufnahmezahl+ICD10Code"
du hast de den wert "1024000028urn:oid:1.3.6.1.4.1.36124.5.9140G47.3" 
G47.3 ist da der ICD10 code. Ist dann 1024000028 die Aufnahmezahl? Woher kommt dann der Rest?

2024-11-04 09:09 UTC, simonesan commented
> AN010

Hab gerade gesehen das AN010 der LKF code bei Procedere ist. Dann hast du da aber die falsche Formatierung für den Timestamp, weil laut Formel die Jahreszahl dort 4-stellig sein sollte? Und darf man da auch den LKF code verwenden, wenn im IG ICD10 steht?

2024-11-06 10:02 UTC, 1anja1 approved these changes

2024-11-06 10:02 UTC, merged